### ISSUE TITLE
Suggestion: return the percentage of missing data for each column

### ISSUE THREAD

**Issue by AndreaPi** [ropensci/visdat#60]
Hi,

I think a nice addition to `vis_dat()` would be the possibility of returning a named vector (or list) containing the names of the columns which have missing data, and the percentage of them. This extra object would not be returned by default, in order not to break existing code which assumes that `vis_dat()` only returns a `ggplot` object. However, you could turn it on through an argument.
 The same addition would be useful for `vis_miss()`: in this case maybe adding a last element in the vector/list containing the total percentage of misses may be useful.

I often have to recompute these quantities by hand in my R Markdown reports which use `visdat`, and it sounds like a waste, given that `visdat` already computes them.

**Comment by njtierney** [comment]
Hi @AndreaPi,

Thanks for your suggestion! I certainly appreciate that having details on the amount of missing data in each column is useful, but I think that it is most useful to have this as a separate function, instead of an argument for `vis_dat()` or `vis_miss()`.

You can find such functions in the [`naniar`](https://github.com/njtierney/naniar) package, which provides tidy data structures, summaries, and visualisations for missing data.

For example,

``` r
library(naniar)

# how many missing in each variable?
miss_var_summary(airquality)
#> # A tibble: 6 x 4
#>   variable n_miss  pct_miss n_miss_cumsum
#>      <chr>  <int>     <dbl>         <int>
#> 1    Ozone     37 24.183007            37
#> 2  Solar.R      7  4.575163            44
#> 3     Wind      0  0.000000            44
#> 4     Temp      0  0.000000            44
#> 5    Month      0  0.000000            44
#> 6      Day      0  0.000000            44

# visualise this?
gg_miss_var(airquality)
```

![](https://i.imgur.com/clgsph4.png)

``` r

# how many missing?
n_miss(airquality)
#> [1] 44

# how many complete?
n_complete(airquality)
#> [1] 874
```

You can read more [here](http://naniar.njtierney.com/articles/getting-started-w-naniar.html)

Let me know if you have any further questions! If I don't hear back from you in about a week I will close this issue, but feel free to reopen, or of course open another issue.

Cheers!

**Comment by AndreaPi** [comment]
@njtierney  nice! I didn't know about [naniar](https://github.com/njtierney/naniar) (I catched the reference to Narnia :-) `miss_var_summary()` is **exactly** what I was looking for. 

But I'm just curious now, if `naniar` has so many plotting functions, why keeping `visdat` as a separate package? I will keep using it because I love its plots  :-) they are colorful but not distracting, in some way they drive the message home. However, it seems like `naniar`  has many plots with a similar intent, so why keeping the packages separed?

**Comment by njtierney** [comment]
Hi @AndreaPi - glad that you got the reference to Narnia! :) double glad to hear that `miss_var_summary()` is what you were looking for!

Good question about `naniar` and `visdat` - this [isn't the first time this question has been asked](https://github.com/ropensci/visdat/issues/54), so perhaps I should think about writing down my reasons somewhere.

My reasoning is that it is easier to maintain each package if they have a narrowly defined scope - the reason I created `visdat` was because these kinds of visualisations are often seen as an afterthought, and so often the package is about something else, rather than just these kinds of "birds eye view" visualisations. It also frees up some mental space - I don't think I would have thought about `vis_cor` or `vis_guess`, or `vis_compare` or the interactive versions of any of the `vis_` family if it were part of a larger package like `naniar`.

It is a good question!

**Comment by AndreaPi** [comment]
Thanks for the explanation! Now that you make me think about it, keeping a narrow scope makes a lot of sense. After all, one of the reasons why I started using `visdat` was exactly that it generated just the visualizations I was looking for, without other fuss (and with nice defaults).
 
One last question, what are `vis_cor`, `vis_guess`, etc.? They don't seem to be functions of either `visdat` or `naniar`. I guess they will be future additions to `visdat` .

**Comment by njtierney** [comment]
Nice defaults! That's a lovely compliment, although I am leveraging heavily on ggplot2 there.

`vis_cor`, `vis_guess` and co are in the development version of `visdat` - which you can access with `devtools::install_github("ropensci/visdat") - they should hopefully be out before Christmas.

Here's some example output of `vis_cor()`

``` r
visdat::vis_cor(airquality)
```

![](https://i.imgur.com/V9FZ72F.png)

Cheers!
